# Generated by Django 6.0.4 on 2026-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('business_name', models.CharField(blank=True, max_length=160, verbose_name='نام کسب\u200cوکار')),
                ('phone', models.CharField(max_length=20, verbose_name='موبایل')),
                ('messenger', models.CharField(blank=True, choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('bale', 'بله'), ('other', 'سایر')], max_length=20, verbose_name='پیام\u200cرسان')),
                ('business_type', models.CharField(blank=True, max_length=60, verbose_name='صنف')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('source', models.CharField(default='landing', max_length=60, verbose_name='منبع')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='تماس گرفته شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'سرنخ',
                'verbose_name_plural': 'سرنخ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
