# Generated by Django 6.0.4 on 2026-06-26

from django.db import migrations, models


def seed_landing_content(apps, schema_editor):
    LandingSettings = apps.get_model('landing', 'LandingSettings')
    SubscriptionPlan = apps.get_model('landing', 'SubscriptionPlan')

    LandingSettings.objects.get_or_create(
        pk=1,
        defaults={
            'demo_bot_url': '',
            'announce_text': 'راه‌اندازی فروشگاهت کمتر از ۱۰ دقیقه طول می‌کشه',
            'stats_label': 'مورد اعتماد فروشگاه‌های پوشاک، آرایشی، خوراکی و …',
            'stat_stores': '+۵۰',
            'stat_orders': '+۱۰۰۰',
            'stat_setup_minutes': '۱۰',
            'pricing_note': 'مطمئن نیستی کدوم مناسبته؟ یه دمو رایگان بگیر، با هم انتخاب می‌کنیم.',
        },
    )

    plans = [
        {
            'name': 'پایه',
            'slug': 'basic',
            'price_label': '۴۹۰٬۰۰۰',
            'price_period': 'تومان / ماه',
            'description': 'ربات + کمپین. مناسب شروع.',
            'features': [
                'ربات بله یا تلگرام',
                'رباتساز بصری',
                'کمپین انبوه',
                'سگمنت‌بندی مخاطب',
            ],
            'is_featured': False,
            'is_active': True,
            'sort_order': 10,
            'button_style': 'outline',
            'cta_label': 'درخواست دمو',
        },
        {
            'name': 'حرفه‌ای',
            'slug': 'pro',
            'price_label': '۹۹۰٬۰۰۰',
            'price_period': 'تومان / ماه',
            'description': 'مینی‌اپ فروشگاه + پرداخت بله + مدیریت سفارش.',
            'features': [
                'همه امکانات پایه',
                'مینی‌اپ فروشگاهی',
                'پرداخت مستقیم بله',
                'مدیریت سفارش و رهگیری',
                'الگوهای آماده صنف',
            ],
            'is_featured': True,
            'is_active': True,
            'sort_order': 20,
            'button_style': 'primary',
            'cta_label': 'شروع کن',
        },
        {
            'name': 'فروشگاهی',
            'slug': 'store',
            'price_label': '۱٬۴۹۰٬۰۰۰',
            'price_period': 'تومان / ماه',
            'description': 'برای فروشگاه‌های پرحجم و حرفه‌ای.',
            'features': [
                'همه امکانات حرفه‌ای',
                'ورود گروهی محصولات',
                'بازیابی سبد رهاشده',
                'پشتیبانی اولویت‌دار',
            ],
            'is_featured': False,
            'is_active': True,
            'sort_order': 30,
            'button_style': 'outline',
            'cta_label': 'درخواست دمو',
        },
    ]
    for data in plans:
        SubscriptionPlan.objects.update_or_create(slug=data['slug'], defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_bot_url', models.URLField(blank=True, default='', max_length=500, verbose_name='لینک ربات نمونه')),
                ('announce_text', models.CharField(default='راه\u200cاندازی فروشگاهت کمتر از ۱۰ دقیقه طول می\u200cکشه', max_length=200, verbose_name='نوار اعلان')),
                ('stats_label', models.CharField(default='مورد اعتماد فروشگاه\u200cهای پوشاک، آرایشی، خوراکی و \u2026', max_length=200, verbose_name='متن نوار آمار')),
                ('stat_stores', models.CharField(default='+۵۰', max_length=40, verbose_name='آمار فروشگاه')),
                ('stat_orders', models.CharField(default='+۱۰۰۰', max_length=40, verbose_name='آمار سفارش')),
                ('stat_setup_minutes', models.CharField(default='۱۰', max_length=40, verbose_name='آمار راه\u200cاندازی (دقیقه)')),
                ('pricing_note', models.CharField(default='مطمئن نیستی کدوم مناسبته؟ یه دمو رایگان بگیر، با هم انتخاب می\u200cکنیم.', max_length=300, verbose_name='یادداشت بخش قیمت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات لندینگ',
                'verbose_name_plural': 'تنظیمات لندینگ',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام پلن')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='شناسه')),
                ('price_label', models.CharField(help_text='مثال: ۴۹۰٬۰۰۰', max_length=40, verbose_name='مبلغ نمایشی')),
                ('price_period', models.CharField(default='تومان / ماه', max_length=40, verbose_name='دوره قیمت')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح کوتاه')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='امکانات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال در لندینگ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('button_style', models.CharField(choices=[('primary', 'اصلی'), ('outline', 'حاشیه\u200cای')], default='outline', max_length=16, verbose_name='استایل دکمه')),
                ('cta_label', models.CharField(default='درخواست دمو', max_length=60, verbose_name='متن دکمه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_landing_content, migrations.RunPython.noop),
    ]
