# Generated by Django 6.0.4 on 2026-06-26

from django.db import migrations, models


SEED_CATEGORIES = [
    ('پوشاک زنانه', 'women-clothing', 10),
    ('پوشاک مردانه', 'men-clothing', 20),
    ('سیسمونی', 'baby-kids', 30),
    ('آرایشی', 'cosmetics', 40),
    ('عطر', 'perfume', 50),
    ('خوراکی خانگی', 'homemade-food', 60),
    ('قنادی', 'bakery', 70),
    ('کافه', 'cafe', 80),
    ('آجیل', 'nuts', 90),
    ('گل و گیاه', 'flowers', 100),
    ('دکوراسیون', 'decor', 110),
    ('زیورآلات', 'jewelry', 120),
    ('کیف و کفش', 'bags-shoes', 130),
    ('لوازم موبایل', 'mobile-accessories', 140),
    ('کتاب', 'books', 150),
    ('ورزشی', 'sports', 160),
    ('اسباب‌بازی', 'toys', 170),
    ('صنایع دستی', 'handicrafts', 180),
    ('عسل و ارگانیک', 'organic-honey', 190),
    ('پت‌شاپ', 'pet-shop', 200),
    ('سالن زیبایی', 'beauty-salon', 210),
    ('آموزشگاه', 'education', 220),
    ('رستوران', 'restaurant', 230),
    ('محصولات دیجیتال', 'digital-products', 240),
    ('سایر', 'other', 999),
]


def seed_business_categories(apps, schema_editor):
    BusinessCategory = apps.get_model('landing', 'BusinessCategory')
    for name, slug, sort_order in SEED_CATEGORIES:
        BusinessCategory.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'sort_order': sort_order,
                'is_active': True,
                'show_on_landing': slug != 'other',
                'is_other': slug == 'other',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landingsettings_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_type_other',
            field=models.CharField(blank=True, max_length=80, verbose_name='صنف (سایر)'),
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام صنف')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='شناسه')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال در فرم لندینگ')),
                ('show_on_landing', models.BooleanField(default=True, verbose_name='نمایش در بخش الگوها')),
                ('is_other', models.BooleanField(default=False, help_text='فقط یک مورد می\u200cتواند گزینه «سایر» باشد.', verbose_name='گزینه سایر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'اصناف',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_business_categories, migrations.RunPython.noop),
    ]
