# Generated by Django 6.0.4 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_businesscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsettings',
            name='brand_favicon_svg',
            field=models.FileField(blank=True, help_text='آیکون تب مرورگر. پیش\u200cفرض: آیکون برند.', upload_to='brand/', verbose_name='فاوآیکون (SVG)'),
        ),
        migrations.AddField(
            model_name='landingsettings',
            name='brand_icon_svg',
            field=models.FileField(blank=True, help_text='آیکون مربعی برای سایدبار و هدر. فرمت SVG با پس\u200cزمینه شفاف.', upload_to='brand/', verbose_name='آیکون برند (SVG)'),
        ),
        migrations.AddField(
            model_name='landingsettings',
            name='brand_logo_svg',
            field=models.FileField(blank=True, help_text='اگر آپلود شود، به\u200cجای آیکون+متن نمایش داده می\u200cشود.', upload_to='brand/', verbose_name='لوگوی افقی (SVG)'),
        ),
        migrations.AddField(
            model_name='landingsettings',
            name='brand_wordmark_accent',
            field=models.CharField(blank=True, default='sell', max_length=40, verbose_name='متن وردمارک (بخش دوم)'),
        ),
        migrations.AddField(
            model_name='landingsettings',
            name='brand_wordmark_primary',
            field=models.CharField(blank=True, default='Rahat', max_length=40, verbose_name='متن وردمارک (بخش اول)'),
        ),
    ]
