# Generated by Django 6.0.5 on 2026-06-28 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_landingsettings_brand_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsettings',
            name='brand_favicon_svg',
            field=models.FileField(blank=True, help_text='آیکون تب مرورگر. پیش\u200cفرض: آیکون برند.', upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='فاوآیکون (SVG)'),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='brand_icon_svg',
            field=models.FileField(blank=True, help_text='آیکون مربعی برای سایدبار و هدر. فرمت SVG با پس\u200cزمینه شفاف.', upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='آیکون برند (SVG)'),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='brand_logo_svg',
            field=models.FileField(blank=True, help_text='اگر آپلود شود، به\u200cجای آیکون+متن نمایش داده می\u200cشود.', upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='لوگوی افقی (SVG)'),
        ),
    ]
