# Generated by Django 6.0.4

from django.db import migrations, models

from landing.terms_default import DEFAULT_TERMS_PAGE_CONTENT, DEFAULT_TERMS_PAGE_TITLE


def seed_terms_content(apps, schema_editor):
    LandingSettings = apps.get_model('landing', 'LandingSettings')
    LandingSettings.objects.filter(pk=1).update(
        terms_page_title=DEFAULT_TERMS_PAGE_TITLE,
        terms_page_content=DEFAULT_TERMS_PAGE_CONTENT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_showcasebot'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsettings',
            name='terms_page_title',
            field=models.CharField(
                default=DEFAULT_TERMS_PAGE_TITLE,
                max_length=120,
                verbose_name='عنوان صفحه قوانین',
            ),
        ),
        migrations.AddField(
            model_name='landingsettings',
            name='terms_page_content',
            field=models.TextField(
                default=DEFAULT_TERMS_PAGE_CONTENT,
                help_text='هر بخش با ## شروع شود. خطوط با - برای فهرست. بین بخش‌ها یک خط خالی بگذارید.',
                verbose_name='متن صفحه قوانین',
            ),
        ),
        migrations.RunPython(seed_terms_content, migrations.RunPython.noop),
    ]
