# Generated by Django 6.0.4

from django.db import migrations

from landing.terms_default import DEFAULT_TERMS_PAGE_CONTENT, DEFAULT_TERMS_PAGE_TITLE


def apply_updated_terms(apps, schema_editor):
    LandingSettings = apps.get_model('landing', 'LandingSettings')
    LandingSettings.objects.filter(pk=1).update(
        terms_page_title=DEFAULT_TERMS_PAGE_TITLE,
        terms_page_content=DEFAULT_TERMS_PAGE_CONTENT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_landingsettings_terms_page'),
    ]

    operations = [
        migrations.RunPython(apply_updated_terms, migrations.RunPython.noop),
    ]
