from django.contrib.auth import views as auth_views
from django.urls import include, path

from balebot import (
    views_miniapp_api,
    views_miniapp_serve,
    views_panel,
    views_panel_catalog,
    views_panel_users,
    views_webhook,
)
from landing import views_panel as landing_views_panel

urlpatterns = [
    path('health/', views_webhook.webhook_health, name='bale_health'),
    path(
        'webhook/<str:platform>/<str:secret>',
        views_webhook.platform_webhook,
        name='platform_webhook',
    ),
    path(
        'webhook/<str:platform>/<str:secret>/',
        views_webhook.platform_webhook,
        name='platform_webhook_slash',
    ),
    path('webhook/<str:secret>', views_webhook.bale_webhook_legacy, name='bale_webhook'),
    path('webhook/<str:secret>/', views_webhook.bale_webhook_legacy, name='bale_webhook_slash'),
    # آدرس قدیمی وب‌هوک وقتی پروژه زیر /bale/ بود
    path('bale/webhook/<str:secret>', views_webhook.bale_webhook_legacy),
    path('bale/webhook/<str:secret>/', views_webhook.bale_webhook_legacy),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='balebot/login.html'),
        name='panel_login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='panel_logout',
    ),
    path('dashboard/', views_panel.DashboardView.as_view(), name='panel_dashboard'),
    path(
        'switch-platform/',
        views_panel.SwitchPlatformView.as_view(),
        name='panel_switch_platform',
    ),
    path(
        'sync-platform/',
        views_panel.PlatformSyncView.as_view(),
        name='panel_sync_platform',
    ),
    path('bot/', views_panel.BotSettingsView.as_view(), name='bot_settings'),
    path('bot/flow/', views_panel.FlowEngineView.as_view(), name='bot_flow_engine'),
    path('subscribers/', views_panel.SubscriberListView.as_view(), name='subscriber_list'),
    path('subscribers/<int:pk>/', views_panel.SubscriberDetailView.as_view(), name='subscriber_detail'),
    path('tags/', views_panel.TagListView.as_view(), name='tag_list'),
    path('tags/<int:pk>/delete/', views_panel.TagDeleteView.as_view(), name='tag_delete'),
    path(
        'bot/flow-media-upload/',
        views_panel.FlowMediaUploadView.as_view(),
        name='flow_media_upload',
    ),
    path('campaigns/', views_panel.CampaignListView.as_view(), name='campaign_list'),
    path('campaigns/new/', views_panel.CampaignCreateView.as_view(), name='campaign_create'),
    path(
        'campaigns/<int:pk>/',
        views_panel.CampaignDetailView.as_view(),
        name='campaign_detail',
    ),
    path(
        'campaigns/<int:pk>/send-batch/',
        views_panel.CampaignSendBatchView.as_view(),
        name='campaign_send_batch',
    ),
    path(
        'campaigns/<int:pk>/edit/',
        views_panel.CampaignUpdateView.as_view(),
        name='campaign_edit',
    ),
    path(
        'campaigns/<int:pk>/delete/',
        views_panel.CampaignDeleteView.as_view(),
        name='campaign_delete',
    ),
    path(
        'campaigns/media-upload/',
        views_panel.CampaignMediaUploadView.as_view(),
        name='campaign_media_upload',
    ),
    path(
        'campaigns/media-upload/clear/',
        views_panel.CampaignMediaClearView.as_view(),
        name='campaign_media_clear',
    ),
    path('callbacks/', views_panel.CallbackLogListView.as_view(), name='callback_log_list'),
    path('inbound/', views_panel.InboundListView.as_view(), name='inbound_list'),
    path('users/', views_panel_users.PanelUserListView.as_view(), name='panel_user_list'),
    path('users/new/', views_panel_users.PanelUserCreateView.as_view(), name='panel_user_create'),
    path('users/<int:pk>/edit/', views_panel_users.PanelUserUpdateView.as_view(), name='panel_user_edit'),
    path('superadmin/', landing_views_panel.SuperAdminDashboardView.as_view(), name='superadmin_dashboard'),
    path('superadmin/leads/', landing_views_panel.SuperAdminLeadListView.as_view(), name='superadmin_lead_list'),
    path('superadmin/leads/<int:pk>/', landing_views_panel.SuperAdminLeadDetailView.as_view(), name='superadmin_lead_detail'),
    path(
        'superadmin/leads/<int:pk>/toggle-contacted/',
        landing_views_panel.SuperAdminLeadToggleContactedView.as_view(),
        name='superadmin_lead_toggle_contacted',
    ),
    path('superadmin/plans/', landing_views_panel.SuperAdminPlanListView.as_view(), name='superadmin_plan_list'),
    path('superadmin/plans/new/', landing_views_panel.SuperAdminPlanCreateView.as_view(), name='superadmin_plan_create'),
    path('superadmin/plans/<int:pk>/edit/', landing_views_panel.SuperAdminPlanUpdateView.as_view(), name='superadmin_plan_edit'),
    path('superadmin/plans/<int:pk>/delete/', landing_views_panel.SuperAdminPlanDeleteView.as_view(), name='superadmin_plan_delete'),
    path(
        'superadmin/business-categories/',
        landing_views_panel.SuperAdminBusinessCategoryListView.as_view(),
        name='superadmin_business_category_list',
    ),
    path(
        'superadmin/business-categories/new/',
        landing_views_panel.SuperAdminBusinessCategoryCreateView.as_view(),
        name='superadmin_business_category_create',
    ),
    path(
        'superadmin/business-categories/<int:pk>/edit/',
        landing_views_panel.SuperAdminBusinessCategoryUpdateView.as_view(),
        name='superadmin_business_category_edit',
    ),
    path(
        'superadmin/business-categories/<int:pk>/delete/',
        landing_views_panel.SuperAdminBusinessCategoryDeleteView.as_view(),
        name='superadmin_business_category_delete',
    ),
    path(
        'superadmin/landing-settings/',
        landing_views_panel.SuperAdminLandingSettingsView.as_view(),
        name='superadmin_landing_settings',
    ),
    path('catalog/', views_panel_catalog.CatalogDashboardView.as_view(), name='catalog_dashboard'),
    path('catalog/onboarding/', views_panel_catalog.CatalogOnboardingView.as_view(), name='catalog_onboarding'),
    path('catalog/templates/', views_panel_catalog.StoreTemplateListView.as_view(), name='catalog_templates'),
    path(
        'catalog/templates/<slug:slug>/apply/',
        views_panel_catalog.StoreTemplateApplyView.as_view(),
        name='catalog_template_apply',
    ),
    path('catalog/import/', views_panel_catalog.CatalogBulkImportView.as_view(), name='catalog_bulk_import'),
    path(
        'catalog/import/sample.xlsx',
        views_panel_catalog.CatalogBulkImportSampleView.as_view(),
        name='catalog_bulk_import_sample',
    ),
    path('catalog/flow/', views_panel_catalog.MiniAppFlowEngineView.as_view(), name='catalog_flow_engine'),
    path('catalog/settings/', views_panel_catalog.CatalogSettingsView.as_view(), name='catalog_settings'),
    path('catalog/categories/', views_panel_catalog.CatalogCategoryListView.as_view(), name='catalog_category_list'),
    path('catalog/categories/new/', views_panel_catalog.CatalogCategoryCreateView.as_view(), name='catalog_category_create'),
    path('catalog/categories/<int:pk>/edit/', views_panel_catalog.CatalogCategoryUpdateView.as_view(), name='catalog_category_edit'),
    path('catalog/items/', views_panel_catalog.CatalogItemListView.as_view(), name='catalog_item_list'),
    path('catalog/items/new/', views_panel_catalog.CatalogItemCreateView.as_view(), name='catalog_item_create'),
    path('catalog/items/<int:pk>/edit/', views_panel_catalog.CatalogItemUpdateView.as_view(), name='catalog_item_edit'),
    path(
        'catalog/items/<int:pk>/media/<int:media_pk>/delete/',
        views_panel_catalog.CatalogItemMediaDeleteView.as_view(),
        name='catalog_item_media_delete',
    ),
    path('catalog/orders/', views_panel_catalog.CatalogOrderListView.as_view(), name='catalog_order_list'),
    path('catalog/orders/<int:pk>/', views_panel_catalog.CatalogOrderDetailView.as_view(), name='catalog_order_detail'),
    path(
        'catalog/orders/<int:pk>/update/',
        views_panel_catalog.CatalogOrderUpdateView.as_view(),
        name='catalog_order_update',
    ),
    path('api/shop/<uuid:public_id>/config/', views_miniapp_api.catalog_config, name='api_catalog_config'),
    path(
        'api/shop/<uuid:public_id>/media/<path:file_path>',
        views_miniapp_api.catalog_media_file,
        name='api_catalog_media',
    ),
    path('api/shop/<uuid:public_id>/categories/', views_miniapp_api.catalog_categories, name='api_catalog_categories'),
    path('api/shop/<uuid:public_id>/items/', views_miniapp_api.catalog_items, name='api_catalog_items'),
    path('api/shop/<uuid:public_id>/items/<slug:slug>/', views_miniapp_api.catalog_item_detail, name='api_catalog_item_detail'),
    path('api/shop/<uuid:public_id>/auth/validate/', views_miniapp_api.catalog_auth_validate, name='api_catalog_auth'),
    path('api/shop/<uuid:public_id>/cart/', views_miniapp_api.catalog_cart, name='api_catalog_cart'),
    path('api/shop/<uuid:public_id>/checkout/', views_miniapp_api.catalog_checkout, name='api_catalog_checkout'),
    path(
        'api/shop/<uuid:public_id>/orders/<int:order_id>/payment/',
        views_miniapp_api.catalog_order_payment,
        name='api_catalog_order_payment',
    ),
    path(
        'api/shop/<uuid:public_id>/orders/<int:order_id>/receipt/',
        views_miniapp_api.catalog_order_receipt,
        name='api_catalog_order_receipt',
    ),
    path('api/shop/<uuid:public_id>/request/', views_miniapp_api.catalog_request, name='api_catalog_request'),
    path('shop/<uuid:public_id>/', views_miniapp_serve.serve_miniapp, name='miniapp_shop'),
    path('shop/<uuid:public_id>/<path:path>', views_miniapp_serve.serve_miniapp, name='miniapp_shop_asset'),
    path('', include('instagram.urls')),
]
