from django.contrib.auth import views as auth_views
from django.urls import include, path

from balebot import (
    views_miniapp_api,
    views_miniapp_serve,
    views_panel,
    views_panel_catalog,
    views_panel_users,
    views_webhook,
)

urlpatterns = [
    path('health/', views_webhook.webhook_health, name='bale_health'),
    path(
        'webhook/<str:platform>/<str:secret>',
        views_webhook.platform_webhook,
        name='platform_webhook',
    ),
    path(
        'webhook/<str:platform>/<str:secret>/',
        views_webhook.platform_webhook,
        name='platform_webhook_slash',
    ),
    path('webhook/<str:secret>', views_webhook.bale_webhook_legacy, name='bale_webhook'),
    path('webhook/<str:secret>/', views_webhook.bale_webhook_legacy, name='bale_webhook_slash'),
    # آدرس قدیمی وب‌هوک وقتی پروژه زیر /bale/ بود
    path('bale/webhook/<str:secret>', views_webhook.bale_webhook_legacy),
    path('bale/webhook/<str:secret>/', views_webhook.bale_webhook_legacy),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='balebot/login.html'),
        name='panel_login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='panel_logout',
    ),
    path('', views_panel.DashboardView.as_view(), name='panel_dashboard'),
    path(
        'switch-platform/',
        views_panel.SwitchPlatformView.as_view(),
        name='panel_switch_platform',
    ),
    path('bot/', views_panel.BotSettingsView.as_view(), name='bot_settings'),
    path('bot/flow/', views_panel.FlowEngineView.as_view(), name='bot_flow_engine'),
    path('subscribers/', views_panel.SubscriberListView.as_view(), name='subscriber_list'),
    path('subscribers/<int:pk>/', views_panel.SubscriberDetailView.as_view(), name='subscriber_detail'),
    path(
        'bot/flow-media-upload/',
        views_panel.FlowMediaUploadView.as_view(),
        name='flow_media_upload',
    ),
    path('campaigns/', views_panel.CampaignListView.as_view(), name='campaign_list'),
    path('campaigns/new/', views_panel.CampaignCreateView.as_view(), name='campaign_create'),
    path(
        'campaigns/<int:pk>/',
        views_panel.CampaignDetailView.as_view(),
        name='campaign_detail',
    ),
    path(
        'campaigns/<int:pk>/edit/',
        views_panel.CampaignUpdateView.as_view(),
        name='campaign_edit',
    ),
    path(
        'campaigns/media-upload/',
        views_panel.CampaignMediaUploadView.as_view(),
        name='campaign_media_upload',
    ),
    path(
        'campaigns/media-upload/clear/',
        views_panel.CampaignMediaClearView.as_view(),
        name='campaign_media_clear',
    ),
    path('callbacks/', views_panel.CallbackLogListView.as_view(), name='callback_log_list'),
    path('inbound/', views_panel.InboundListView.as_view(), name='inbound_list'),
    path('users/', views_panel_users.PanelUserListView.as_view(), name='panel_user_list'),
    path('users/new/', views_panel_users.PanelUserCreateView.as_view(), name='panel_user_create'),
    path('users/<int:pk>/edit/', views_panel_users.PanelUserUpdateView.as_view(), name='panel_user_edit'),
    path('catalog/', views_panel_catalog.CatalogDashboardView.as_view(), name='catalog_dashboard'),
    path('catalog/flow/', views_panel_catalog.MiniAppFlowEngineView.as_view(), name='catalog_flow_engine'),
    path('catalog/settings/', views_panel_catalog.CatalogSettingsView.as_view(), name='catalog_settings'),
    path('catalog/categories/', views_panel_catalog.CatalogCategoryListView.as_view(), name='catalog_category_list'),
    path('catalog/categories/new/', views_panel_catalog.CatalogCategoryCreateView.as_view(), name='catalog_category_create'),
    path('catalog/categories/<int:pk>/edit/', views_panel_catalog.CatalogCategoryUpdateView.as_view(), name='catalog_category_edit'),
    path('catalog/items/', views_panel_catalog.CatalogItemListView.as_view(), name='catalog_item_list'),
    path('catalog/items/new/', views_panel_catalog.CatalogItemCreateView.as_view(), name='catalog_item_create'),
    path('catalog/items/<int:pk>/edit/', views_panel_catalog.CatalogItemUpdateView.as_view(), name='catalog_item_edit'),
    path(
        'catalog/items/<int:pk>/media/<int:media_pk>/delete/',
        views_panel_catalog.CatalogItemMediaDeleteView.as_view(),
        name='catalog_item_media_delete',
    ),
    path('catalog/orders/', views_panel_catalog.CatalogOrderListView.as_view(), name='catalog_order_list'),
    path('catalog/orders/<int:pk>/', views_panel_catalog.CatalogOrderDetailView.as_view(), name='catalog_order_detail'),
    path('api/shop/<uuid:public_id>/config/', views_miniapp_api.catalog_config, name='api_catalog_config'),
    path(
        'api/shop/<uuid:public_id>/media/<path:file_path>',
        views_miniapp_api.catalog_media_file,
        name='api_catalog_media',
    ),
    path('api/shop/<uuid:public_id>/categories/', views_miniapp_api.catalog_categories, name='api_catalog_categories'),
    path('api/shop/<uuid:public_id>/items/', views_miniapp_api.catalog_items, name='api_catalog_items'),
    path('api/shop/<uuid:public_id>/items/<slug:slug>/', views_miniapp_api.catalog_item_detail, name='api_catalog_item_detail'),
    path('api/shop/<uuid:public_id>/auth/validate/', views_miniapp_api.catalog_auth_validate, name='api_catalog_auth'),
    path('api/shop/<uuid:public_id>/cart/', views_miniapp_api.catalog_cart, name='api_catalog_cart'),
    path('api/shop/<uuid:public_id>/checkout/', views_miniapp_api.catalog_checkout, name='api_catalog_checkout'),
    path('api/shop/<uuid:public_id>/request/', views_miniapp_api.catalog_request, name='api_catalog_request'),
    path(
        'shop/<uuid:public_id>/payment/zarinpal/callback/',
        views_miniapp_serve.zarinpal_callback,
        name='zarinpal_callback',
    ),
    path('shop/<uuid:public_id>/', views_miniapp_serve.serve_miniapp, name='miniapp_shop'),
    path('shop/<uuid:public_id>/<path:path>', views_miniapp_serve.serve_miniapp, name='miniapp_shop_asset'),
    path('', include('instagram.urls')),
]
