"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def env_bool(key: str, default: bool = False) -> bool:
    v = os.environ.get(key)
    if v is None:
        return default
    return v.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(key: str, default: str = '') -> list[str]:
    raw = os.environ.get(key, default)
    if not raw.strip():
        return []
    return [x.strip() for x in raw.split(',') if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'balebot',
    'instagram',
    'landing',
]

SERVE_STATIC_VIA_DJANGO = env_bool('SERVE_STATIC_VIA_DJANGO', False)
SERVE_STATIC = config('SERVE_STATIC', default=True, cast=bool)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'balebot.middleware.MiniAppFrameMiddleware',
]

if SERVE_STATIC_VIA_DJANGO:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'balebot.context_processors.panel_branding',
                'core.context_processors.site_brand',
                'landing.context_processors.landing_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# مقادیر را در .env با POSTGRES_* بگذارید؛ دیتابیس را از قبل در PostgreSQL بسازید.

POSTGRES_DB = os.environ.get('POSTGRES_DB', 'balebot')
POSTGRES_USER = os.environ.get('POSTGRES_USER', 'postgres')
POSTGRES_PASSWORD = os.environ.get('POSTGRES_PASSWORD', '')
POSTGRES_HOST = os.environ.get('POSTGRES_HOST', 'localhost')
POSTGRES_PORT = os.environ.get('POSTGRES_PORT', '5432')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
        'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '300')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'fa-ir')

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Asia/Tehran')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = config('STATIC_URL', default='/public/static/')
STATIC_ROOT = config('STATIC_ROOT', default=os.path.join(BASE_DIR, 'public', 'static'))

# Static files storage with versioning (for cache busting)
# Use ManifestStaticFilesStorage in production for automatic versioning
if not DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
elif SERVE_STATIC_VIA_DJANGO:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = config('MEDIA_URL', default='/public/media/')
MEDIA_ROOT = config('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'public', 'media'))
# سرو فایل‌های media از خود Django (برای مینی‌اپ و پنل). در پروداکشن ترجیحاً nginx همین مسیر را سرو کند.
SERVE_MEDIA = config('SERVE_MEDIA', default=True, cast=bool)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Campaign sending
CAMPAIGN_SEND_DELAY_MS = int(os.environ.get('CAMPAIGN_SEND_DELAY_MS', '80'))
CAMPAIGN_SEND_BATCH_SIZE = int(os.environ.get('CAMPAIGN_SEND_BATCH_SIZE', '20'))
# Legacy env vars (migrated to BotSettings in DB on first migrate)
_LEGACY_BALE_BOT_TOKEN = os.environ.get('BALE_BOT_TOKEN', '')
_LEGACY_BALE_WEBHOOK_SECRET = os.environ.get('BALE_WEBHOOK_SECRET', '')
_LEGACY_BALE_WEBHOOK_PUBLIC_URL = os.environ.get('BALE_WEBHOOK_PUBLIC_URL', '').strip()
# آدرس عمومی HTTPS سرور (برای وب‌هوک، مینی‌اپ و لینک‌های مطلق)
BASE_URL = config('BASE_URL', default=_LEGACY_BALE_WEBHOOK_PUBLIC_URL).strip()
# حداکثر حجم آپلود ویدیوی کمپین (مگابایت) — در ویوی آپلود بررسی می‌شود
CAMPAIGN_VIDEO_MAX_UPLOAD_MB = int(os.environ.get('CAMPAIGN_VIDEO_MAX_UPLOAD_MB', '120'))

# ویدیو آموزش بکاپ دایرکت اینستاگرام (YouTube / Aparat / embed URL)
INSTAGRAM_BACKUP_TUTORIAL_VIDEO_URL = config(
    'INSTAGRAM_BACKUP_TUTORIAL_VIDEO_URL',
    default='',
).strip()

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

LANDING_ADMIN_CHAT_ID = config('LANDING_ADMIN_CHAT_ID', default='').strip()
LANDING_DEMO_BOT_URL = config(
    'LANDING_DEMO_BOT_URL',
    default='https://ble.ir/your_demo_bot',
).strip()

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Redis / Celery
REDIS_URL = (os.environ.get('REDIS_URL') or '').strip()
CELERY_BROKER_URL = (os.environ.get('CELERY_BROKER_URL') or REDIS_URL or '').strip()
CELERY_RESULT_BACKEND = (
    os.environ.get('CELERY_RESULT_BACKEND') or REDIS_URL or ''
).strip()

_broker_configured = bool(CELERY_BROKER_URL)
_webhook_celery_env = os.environ.get('WEBHOOK_USE_CELERY')
if _webhook_celery_env is None:
    WEBHOOK_USE_CELERY = _broker_configured
else:
    WEBHOOK_USE_CELERY = env_bool('WEBHOOK_USE_CELERY', False)

CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', False)
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_TASK_ROUTES = {
    'balebot.tasks.process_webhook_update': {'queue': 'webhooks'},
    'balebot.tasks.run_due_campaigns': {'queue': 'campaigns'},
}

CELERY_BEAT_SCHEDULE = {
    'process-campaigns': {
        'task': 'balebot.tasks.run_due_campaigns',
        'schedule': 120.0,
    },
}

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        },
    }

# Gunicorn (read by gunicorn.conf.py)
GUNICORN_WORKERS = int(os.environ.get('GUNICORN_WORKERS', '4'))
GUNICORN_THREADS = int(os.environ.get('GUNICORN_THREADS', '2'))
GUNICORN_TIMEOUT = int(os.environ.get('GUNICORN_TIMEOUT', '30'))
