# Generated by Django 6.0.4 on 2026-06-16 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balebot', '0028_flowmedia_media_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام حوزه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_activity_domains', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'حوزه فعالیت',
                'verbose_name_plural': 'حوزه\u200cهای فعالیت',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_domain_custom', models.CharField(blank=True, default='', max_length=120, verbose_name='حوزه سفارشی')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'در حال اجرا'), ('completed', 'تمام\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='running', max_length=16)),
                ('phone_count', models.PositiveIntegerField(default=0)),
                ('json_files_scanned', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to='instagram.activitydomain')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_extraction_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_extraction_jobs', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'عملیات استخراج',
                'verbose_name_plural': 'عملیات\u200cهای استخراج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11)),
                ('activity_domain_label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_extracted_phones', to='balebot.workspace')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='instagram.extractionjob')),
            ],
            options={
                'verbose_name': 'شماره استخراج\u200cشده',
                'verbose_name_plural': 'شماره\u200cهای استخراج\u200cشده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitydomain',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='instagram_activitydomain_workspace_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='extractedphone',
            index=models.Index(fields=['workspace', 'activity_domain_label'], name='instagram_e_workspa_679862_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedphone',
            index=models.Index(fields=['workspace', 'phone_number'], name='instagram_e_workspa_9b81de_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedphone',
            constraint=models.UniqueConstraint(fields=('job', 'phone_number'), name='instagram_extractedphone_job_phone_uniq'),
        ),
    ]
