# Generated by Django 6.0.7 on 2026-07-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0046_catalogitem_canonical_key_and_more'),
        ('instagram', '0002_instagram_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconnection',
            name='auth_provider',
            field=models.CharField(choices=[('instagram_login', 'Instagram Login'), ('facebook_login_legacy', 'Facebook Login (legacy)')], db_index=True, default='facebook_login_legacy', max_length=32),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='capability_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='token_last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='webhook_subscribed_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagramcontact',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_contacts', to='balebot.customerprofile'),
        ),
        migrations.AddField(
            model_name='instagramconversation',
            name='last_customer_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='claimed_session_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='code_digest',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='is_single_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstagramStorefrontConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('secure_link_hours', models.PositiveSmallIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_storefronts', to='balebot.catalogsettings')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_storefront', to='balebot.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAutomationActionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_runs', to='instagram.instagramwebhookevent')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_runs', to='instagram.instagramautomationrule')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_action_runs', to='balebot.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'rule', 'action_key'), name='ig_action_event_rule_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_media_id', models.CharField(db_index=True, max_length=128)),
                ('media_type', models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_ALBUM', 'Carousel'), ('STORY', 'Story'), ('REEL', 'Reel')], default='', max_length=32)),
                ('media_product_type', models.CharField(blank=True, default='', max_length=32)),
                ('caption', models.TextField(blank=True, default='')),
                ('permalink', models.URLField(blank=True, default='', max_length=2048)),
                ('media_url', models.URLField(blank=True, default='', max_length=2048)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=2048)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='instagram.instagramconnection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_media_bindings', to='balebot.catalogitem')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_media', to='balebot.workspace')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'media_type', 'is_active'], name='instagram_i_workspa_ae9edb_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_media_id'), name='ig_media_connection_external_uniq')],
            },
        ),
    ]
