# Generated by Django 6.0.7 on 2026-07-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagramconnection_auth_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramtrackedlink',
            name='source_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='instagram.instagrammedia'),
        ),
    ]
