# Generated by Django 6.0.5 on 2026-05-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'متن'), ('text_buttons', 'متن + دکمهٔ اینلاین'), ('photo', 'عکس'), ('video', 'ویدیو'), ('voice', 'صدا'), ('document', 'سند')], max_length=32)),
                ('body', models.TextField(blank=True, default='', help_text='متن یا زیرنویس رسانه')),
                ('media', models.FileField(blank=True, null=True, upload_to='campaigns/%Y/%m/')),
                ('inline_keyboard', models.JSONField(blank=True, default=list, help_text='لیست ردیف\u200cها: هر ردیف آرایه\u200cای از {text, callback_data}')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('queued', 'در صف'), ('sending', 'در حال ارسال'), ('completed', 'تمام\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='draft', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bale_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('is_registered', models.BooleanField(default=False, help_text='پس از ارسال شماره تماس از طریق دکمهٔ تماس فعال می\u200cشود.')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال، در کمپین\u200cها ارسال نمی\u200cشود.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'متن'), ('voice', 'صدا'), ('photo', 'عکس'), ('video', 'ویدیو'), ('document', 'فایل'), ('contact', 'مخاطب'), ('other', 'سایر')], max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('file_id', models.CharField(blank=True, default='', max_length=512)),
                ('local_file', models.FileField(blank=True, null=True, upload_to='inbound/%Y/%m/')),
                ('bale_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='balebot.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_query_id', models.CharField(db_index=True, max_length=128)),
                ('data', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='balebot.campaign')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='balebot.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال\u200cشده'), ('failed', 'خطا')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='balebot.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_deliveries', to='balebot.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subscriber'), name='unique_campaign_subscriber_delivery')],
            },
        ),
    ]
