# Generated by Django 6.0.5 on 2026-05-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('panel_brand_title', models.CharField(default='کنترل بازو', max_length=120, verbose_name='عنوان پنل (نوار کناری)')),
                ('panel_brand_subtitle', models.CharField(blank=True, default='مدیریت کمپین و مخاطبان', max_length=180, verbose_name='زیرعنوان پنل')),
                ('welcome_message', models.TextField(default='سلام! برای ثبت\u200cنام و دریافت اطلاعیه\u200cها، شمارهٔ خود را با دکمهٔ زیر ارسال کنید.', verbose_name='پیام خوش\u200cآمدگویی (/start)')),
                ('contact_button_label', models.CharField(default='ارسال شماره تماس', max_length=64, verbose_name='برچسب دکمهٔ تماس')),
                ('registration_success_message', models.TextField(default='ثبت\u200cنام با موفقیت انجام شد. می\u200cتوانید از طریق همین بازو پیام\u200cهای ما را دریافت کنید.', verbose_name='پیام پس از دریافت شماره')),
                ('unsubscribe_message', models.TextField(default='اشتراک شما غیرفعال شد. هر زمان بخواهید دوباره /start بزنید.', verbose_name='پیام خروج (/stop)')),
                ('callback_ack_message', models.CharField(default='ثبت شد', max_length=200, verbose_name='اعلان کوتاه پس از کلیک دکمهٔ اینلاین')),
                ('help_message', models.TextField(blank=True, default='راهنما: با /start ثبت\u200cنام کنید. با /stop اطلاعیه\u200cها را قطع کنید.', verbose_name='متن دستور /help')),
                ('collect_contact_on_start', models.BooleanField(default=True, verbose_name='نمایش دکمهٔ ارسال شماره بعد از /start')),
                ('enable_help_command', models.BooleanField(default=True, verbose_name='فعال بودن دستور /help')),
                ('enable_stop_command', models.BooleanField(default=True, verbose_name='فعال بودن دستور /stop')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات بازو',
                'verbose_name_plural': 'تنظیمات بازو',
            },
        ),
    ]
