# Generated by Django 6.0.4 on 2026-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0004_subscriber_menu_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='schedule_kind',
            field=models.CharField(choices=[('instant', 'آنی'), ('scheduled', 'زمان\u200cبندی\u200cشده')], default='instant', help_text='آنی: بلافاصله پس از قرار گرفتن در صف؛ زمان\u200cبندی\u200cشده: در تاریخ و ساعت شمسی تعیین\u200cشده.', max_length=16, verbose_name='نوع زمان ارسال'),
        ),
    ]
