# Generated by Django 6.0.4 on 2026-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0006_botsettings_split_start_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='enable_support',
            field=models.BooleanField(default=False, verbose_name='فعال بودن پشتیبانی'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='support_button_label',
            field=models.CharField(default='پیام به پشتیبانی', max_length=64, verbose_name='برچسب دکمهٔ پشتیبانی'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='support_start_prompt_message',
            field=models.TextField(default='برای ارسال پیام به پشتیبانی روی دکمهٔ زیر بزنید.', verbose_name='متن راهنمای شروع پشتیبانی'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='support_waiting_message',
            field=models.TextField(default='پیام شما ثبت شد. لطفاً منتظر پاسخ پشتیبانی باشید.', verbose_name='پیام ثبت درخواست پشتیبانی'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='is_support_request',
            field=models.BooleanField(default=False, help_text='اگر این پیام در جریان «پیام به پشتیبانی» ثبت شده باشد روشن است.'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='awaiting_support_message',
            field=models.BooleanField(default=False, help_text='اگر روشن باشد، پیام بعدی کاربر به عنوان پیام پشتیبانی ثبت می\u200cشود.'),
        ),
    ]
