# Generated by Django 6.0.4 on 2026-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0007_botsettings_enable_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='is_support_read',
            field=models.BooleanField(default=False, help_text='فقط برای پیام\u200cهای پشتیبانی: آیا توسط ادمین دیده شده است؟'),
        ),
    ]
