# Generated by Django 6.0.4 on 2026-05-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0008_inboundmessage_is_support_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'کاربر'), ('admin', 'ادمین')], max_length=16)),
                ('kind', models.CharField(choices=[('text', 'متن'), ('photo', 'عکس'), ('video', 'ویدیو'), ('voice', 'صدا'), ('document', 'فایل'), ('other', 'سایر')], default='text', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('file_id', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_items', to='balebot.inboundmessage')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_messages', to='balebot.subscriber')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
