# Generated by Django 6.0.4 on 2026-05-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0009_supportticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmessage',
            name='parent_user_message',
            field=models.ForeignKey(blank=True, help_text='برای پاسخ ادمین: پیام کاربرِ مبنای این تیکت.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_replies', to='balebot.supportticketmessage'),
        ),
    ]
