# Generated by Django 6.0.4 on 2026-05-12 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0010_supportticketmessage_parent_user_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tag_type', models.CharField(choices=[('class', 'کلاس'), ('generic', 'عمومی')], db_index=True, default='generic', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='شناسهٔ مشترکین نهایی این کمپین در زمان صف\u200cبندی.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subscriber_tags', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_tags', to='balebot.subscriber')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_tags', to='balebot.tag')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='balebot.subscriber')),
                ('tag', models.ForeignKey(limit_choices_to={'tag_type': 'class'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='balebot.tag')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_tags',
            field=models.ManyToManyField(blank=True, help_text='اگر انتخاب شود، کمپین فقط برای اعضای همین برچسب\u200cها صف می\u200cشود.', related_name='campaigns', to='balebot.tag'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='balebot.SubscriberTag', to='balebot.tag'),
        ),
        migrations.AddConstraint(
            model_name='subscribertag',
            constraint=models.UniqueConstraint(fields=('subscriber', 'tag'), name='unique_subscriber_tag'),
        ),
        migrations.AddIndex(
            model_name='classenrollmentrequest',
            index=models.Index(fields=['status', 'requested_at'], name='balebot_cla_status_d819a3_idx'),
        ),
    ]
