# Generated by Django 6.0.4 on 2026-05-24 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0011_tag_campaign_audience_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='flow_media/%Y/%m/')),
                ('bale_file_id', models.CharField(blank=True, default='', max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='botsettings',
            name='start_flow',
            field=models.JSONField(blank=True, default=dict, help_text='جریان پس از /start: sequence از متن، عکس و دکمه با اکشن\u200cهای تو در تو.'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='start_flow_default_text',
            field=models.TextField(blank=True, default='گزینه\u200cای برای ادامه در دسترس نیست.', help_text='وقتی مسیر دکمه به جایی وصل نیست یا اکشن نامعتبر است.', verbose_name='متن پیش\u200cفرض جریان (بن\u200cبست)'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='start_inline_keyboard',
            field=models.JSONField(blank=True, default=dict, help_text='(منسوخ) — از start_flow استفاده کنید.'),
        ),
    ]
