# Generated by Django 6.0.5 on 2026-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0016_workspace_multi_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
