# Generated by Django 6.0.4 on 2026-06-05 20:25

import balebot.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0019_workspace_platform_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allow_bale_miniapp',
            field=models.BooleanField(default=False, verbose_name='دسترسی مینی\u200cاپ بله'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='allow_telegram_miniapp',
            field=models.BooleanField(default=False, verbose_name='دسترسی مینی\u200cاپ تلگرام'),
        ),
        migrations.CreateModel(
            name='CatalogCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], default='bale', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_carts', to='balebot.subscriber')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_carts', to='balebot.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, default='bale', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='balebot.catalogcategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'دسته فروشگاه',
                'verbose_name_plural': 'دسته\u200cهای فروشگاه',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, default='bale', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('short_description', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('product', 'محصول'), ('portfolio', 'نمونه\u200cکار'), ('service', 'خدمت'), ('digital', 'دیجیتال')], default='product', max_length=16)),
                ('price', models.PositiveBigIntegerField(blank=True, help_text='قیمت به ریال', null=True)),
                ('sale_mode', models.CharField(choices=[('buyable', 'قابل خرید'), ('request_only', 'فقط درخواست'), ('both', 'خرید و درخواست')], default='both', max_length=16)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='balebot.catalogcategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'آیتم فروشگاه',
                'verbose_name_plural': 'آیتم\u200cهای فروشگاه',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='balebot.catalogcart')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_entries', to='balebot.catalogitem')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/items/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='balebot.catalogitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, default='bale', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده'), ('request', 'درخواست')], db_index=True, default='pending', max_length=16)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('payment_charge_id', models.CharField(blank=True, default='', max_length=256)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_orders', to='balebot.subscriber')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_orders', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'سفارش فروشگاه',
                'verbose_name_plural': 'سفارش\u200cهای فروشگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=200)),
                ('price_snapshot', models.PositiveBigIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balebot.catalogitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='balebot.catalogorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, default='bale', max_length=16)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('provider_token', models.CharField(blank=True, default='', max_length=256, verbose_name='توکن پرداخت')),
                ('hero_title', models.CharField(blank=True, default='', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='catalog/%Y/%m/')),
                ('theme_config', models.JSONField(blank=True, default=balebot.models.default_catalog_theme)),
                ('labels', models.JSONField(blank=True, default=balebot.models.default_catalog_labels)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_settings', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
        migrations.AddConstraint(
            model_name='catalogcart',
            constraint=models.UniqueConstraint(fields=('workspace', 'platform', 'subscriber'), name='unique_catalog_cart_per_subscriber'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'platform', 'slug'), name='unique_catalog_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('workspace', 'platform', 'slug'), name='unique_catalog_item_slug'),
        ),
        migrations.AddConstraint(
            model_name='catalogcartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'catalog_item'), name='unique_cart_catalog_item'),
        ),
        migrations.AddConstraint(
            model_name='catalogsettings',
            constraint=models.UniqueConstraint(fields=('workspace', 'platform'), name='unique_catalog_settings_workspace_platform'),
        ),
    ]
