# Generated by Django 6.0.4 on 2026-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0020_workspace_miniapp_and_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogorder',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='zarinpal_authority',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='admin_notify_chat_id',
            field=models.BigIntegerField(blank=True, help_text='شناسه گفتگوی ادمین در بله/تلگرام برای دریافت سبد خرید.', null=True, verbose_name='چت\u200cآیدی ادمین برای سفارش\u200cها'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='payment_admin_enabled',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی ارسال سبد به ادمین'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='payment_default_method',
            field=models.CharField(choices=[('admin_cart', 'ارسال سبد به ادمین'), ('zarinpal', 'زرین\u200cپال')], default='admin_cart', max_length=16, verbose_name='روش پرداخت پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='payment_zarinpal_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی زرین\u200cپال'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='zarinpal_merchant_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='مرچنت\u200cآیدی زرین\u200cپال'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='zarinpal_sandbox',
            field=models.BooleanField(default=True, verbose_name='حالت تست زرین\u200cپال (سندباکس)'),
        ),
        migrations.AlterField(
            model_name='catalogsettings',
            name='provider_token',
            field=models.CharField(blank=True, default='', help_text='دیگر استفاده نمی\u200cشود؛ از زرین\u200cپال یا ارسال به ادمین استفاده کنید.', max_length=256, verbose_name='توکن پرداخت (منسوخ)'),
        ),
    ]
