# Generated by Django 6.0.5 on 2026-06-09 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0022_catalog_media_and_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitemmedia',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='balebot.catalogitem'),
        ),
        migrations.AlterField(
            model_name='catalogsettings',
            name='payment_admin_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی ارسال سبد به ادمین'),
        ),
    ]
