# Generated by Django 6.0.4 on 2026-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0028_flowmedia_media_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allow_instagram',
            field=models.BooleanField(default=False, verbose_name='دسترسی اینستاگرام'),
        ),
    ]
