# Generated by Django 6.0.4 on 2026-06-24 18:54

import balebot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0035_store_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcart',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='customer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='discount_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده'), ('cancelled', 'لغو\u200cشده'), ('returned', 'مرجوعی')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='recipient_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='recipient_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='shipping_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='abandoned_cart_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='ساعت انتظار قبل از یادآوری سبد'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='abandoned_cart_message_template',
            field=models.TextField(blank=True, default='سبد خریدت منتظرته 🛍 با کد {code} ۱۰٪ تخفیف بگیر.', verbose_name='پیام سبد رها\u200cشده'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='free_shipping_threshold',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='آستانه ارسال رایگان (ریال)'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='order_notify_delivered_template',
            field=models.TextField(blank=True, default='سفارش شما تحویل داده شد. ممنون از خریدتان 🌹', verbose_name='پیام وضعیت «تحویل\u200cشده»'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='order_notify_shipped_template',
            field=models.TextField(blank=True, default='سفارش شما ارسال شد 📦 کد رهگیری: {tracking_code}', verbose_name='پیام وضعیت «ارسال\u200cشده»'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='shipping_by_province',
            field=models.JSONField(blank=True, default=dict, verbose_name='هزینه ارسال به تفکیک استان'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='shipping_flat_cost',
            field=models.BigIntegerField(default=0, verbose_name='هزینه ثابت ارسال (ریال)'),
        ),
        migrations.AddField(
            model_name='catalogsettings',
            name='shipping_mode',
            field=models.CharField(choices=[('free', 'رایگان'), ('flat', 'ثابت'), ('by_province', 'بر اساس استان')], default='flat', max_length=20, verbose_name='روش محاسبه ارسال'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='body',
            field=models.TextField(blank=True, default='', help_text='متن اصلی پیام یا زیرنویس رسانه', verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content_type',
            field=models.CharField(choices=[('text', 'متن'), ('text_buttons', 'متن + دکمهٔ اینلاین'), ('photo', 'عکس'), ('video', 'ویدیو'), ('voice', 'صدا'), ('document', 'فایل')], max_length=32, verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='media',
            field=models.FileField(blank=True, help_text='برای عکس، ویدیو یا فایل — بسته به نوع محتوا', null=True, upload_to='campaigns/%Y/%m/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان کمپین'),
        ),
        migrations.AlterField(
            model_name='catalogorder',
            name='public_token',
            field=models.CharField(db_index=True, default=balebot.models._order_public_token, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogsettings',
            name='channel_membership_message',
            field=models.TextField(blank=True, default='برای استفاده از مینی\u200cاپ ابتدا در کانال ما عضو شوید.', verbose_name='پیام عضویت کانال'),
        ),
        migrations.AlterField(
            model_name='catalogsettings',
            name='payment_default_method',
            field=models.CharField(choices=[('admin_cart', 'ارسال سبد به ادمین'), ('zarinpal', 'زرین\u200cپال'), ('bale', 'پرداخت بله')], default='admin_cart', max_length=16, verbose_name='روش پرداخت پیش\u200cفرض'),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, default='bale', max_length=16)),
                ('code', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغی')], max_length=10)),
                ('value', models.BigIntegerField(help_text='درصد یا مبلغ به ریال')),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('min_order_amount', models.BigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'platform', 'code'), name='unique_discount_code_workspace_platform')],
            },
        ),
    ]
