# Generated by Django 6.0.4 on 2026-06-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0041_catalogitem_flash_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='خالی = بدون محدودیت زمانی.', null=True, verbose_name='تاریخ انقضای اشتراک'),
        ),
    ]
