# Generated by Django 6.0.4 on 2026-07-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0042_workspace_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='first_purchase_only',
            field=models.BooleanField(default=False, help_text='فقط برای مشتری بدون سفارش پرداخت\u200cشده قبلی'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_discount_amount',
            field=models.BigIntegerField(blank=True, help_text='سقف مبلغ تخفیف به ریال (برای کدهای درصدی)', null=True),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='collect_contact_on_start',
            field=models.BooleanField(default=False, verbose_name='نمایش دکمهٔ ارسال شماره بعد از /start'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='start_message_normal',
            field=models.TextField(blank=True, default='', help_text='منسوخ — خوش\u200cآمد را در طراحی منوی /start قرار دهید. فقط وقتی منو خالی است و این فیلد پر باشد ارسال می\u200cشود.', verbose_name='پیام /start معمولی'),
        ),
    ]
