# Generated by Django 6.0.7 on 2026-07-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0043_discount_code_rules_and_bot_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitemmedia',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='لینک مستقیم ویدیو یا فایل (جایگزین آپلود)', max_length=500),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'محصول'), ('download', 'فایل دانلود'), ('video', 'ویدیو و آموزش'), ('course', 'دوره آموزشی'), ('package', 'پکیج فایل'), ('showcase', 'معرفی و نمونه\u200cکار')], default='product', max_length=16),
        ),
        migrations.AlterField(
            model_name='catalogitemmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/items/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='catalogsettings',
            name='bale_payment_card_number',
            field=models.CharField(blank=True, default='', help_text='به\u200cعنوان provider_token در sendInvoice استفاده می\u200cشود.', max_length=32, verbose_name='توکن پرداخت بله (provider_token)'),
        ),
        migrations.CreateModel(
            name='CatalogEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, default='bale', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='balebot.catalogitem')),
                ('source_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='balebot.catalogorderline')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entitlements', to='balebot.subscriber')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entitlements', to='balebot.workspace')),
            ],
            options={
                'verbose_name': 'دسترسی محتوا',
                'verbose_name_plural': 'دسترسی\u200cهای محتوا',
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'item'), name='unique_catalog_entitlement_per_subscriber_item')],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False, help_text='پیش\u200cنمایش رایگان حتی بدون خرید')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of_groups', to='balebot.catalogitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='balebot.catalogitem')),
            ],
            options={
                'verbose_name': 'عضو دوره/پکیج',
                'verbose_name_plural': 'اعضای دوره/پکیج',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='unique_catalog_item_member')],
            },
        ),
    ]
