# Generated by Django 6.0.7 on 2026-07-23 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0045_catalog_order_c2c_pending_status'),
        ('instagram', '0002_instagram_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='canonical_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='شناسه مشترک محصول در نسخه\u200cهای بله و تلگرام'),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='instagram_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_orders', to='instagram.instagramcontact'),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='instagram_tracked_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_orders', to='instagram.instagramtrackedlink'),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('bale', 'بله'), ('telegram', 'تلگرام'), ('instagram', 'اینستاگرام')], db_index=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='balebot.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_orders', to='balebot.customerprofile'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='balebot.customerprofile'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_phone__gt', ''), ('phone_verified_at__isnull', False)), fields=('workspace', 'normalized_phone'), name='customer_verified_phone_workspace_uniq'),
        ),
    ]
