# Generated by Django 6.0.7 on 2026-07-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balebot', '0047_backfill_customer_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='bot_public_username',
            field=models.CharField(blank=True, default='', help_text='Public bot username used for one-time delivery deep links.', max_length=128),
        ),
        migrations.CreateModel(
            name='CatalogDeliveryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('telegram', 'تلگرام')], db_index=True, max_length=16)),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_delivery_tokens', to='balebot.subscriber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tokens', to='balebot.catalogorder')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'platform', 'created_at'], name='balebot_cat_order_i_42a4a3_idx')],
            },
        ),
    ]
